"use client";

import React, { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence, useScroll, useTransform } from "motion/react";
import { X, ArrowUpRight, ChevronLeft, ChevronRight, CheckCircle2, AlertCircle, Info, Activity, Database, Cpu, Layers, Zap } from "lucide-react";
import Image from "next/image";
import { cn } from "@/lib/utils";
import { useSection } from "@/context/SectionContext";

interface CaseStudyOverlayProps {
  projectId: string | null;
}

const PROJECT_ORDER = ["hivestate", "resolveos", "burnsight"];

interface ProjectSection {
  title: string;
  desc: string;
  icon?: React.ReactNode;
  step?: string;
}

interface ProjectData {
  name: string;
  systemNumber: string;
  subheading: string;
  description: string;
  image: string;
  accent: string;
  sections: {
    need: string;
    painPoints?: ProjectSection[];
    systemIdea: string;
    coreEngine?: ProjectSection[];
    hitl?: ProjectSection[];
    dataEngine?: {
        steps: ProjectSection[];
    };
    stack: { category: string; items: string[] }[];
    highlights?: ProjectSection[];
    reality: {
        built: string[];
        mocked: string[];
        gap: string[];
    };
    roadmap: ProjectSection[];
  };
}

const PROJECTS_DATA: Record<string, ProjectData> = {
  burnsight: {
    name: "BurnSight",
    systemNumber: "03 // SYSTEM",
    subheading: "FINOPS ENGINE // SPEND FORENSICS",
    description: "Agentic financial command center that connects directly to your financial data, canonicalizes dirty vendor records, and runs deterministic logic to surface guaranteed cash leaks — not probabilistic guesses.",
    image: "/projects/burnsight.png",
    accent: "#FFD700",
    sections: {
      need: "Startups hemorrhage cash through ghost licenses, forgotten trials, and duplicate tooling — invisibly. Generic burn dashboards show totals but never tell you what to cut or why. BurnSight bridges that gap with forensic-grade detection that proves waste before flagging it.",
      painPoints: [
        { title: "GHOST LICENSES", desc: "Software seats still billed for employees who left months ago." },
        { title: "FREE TRIAL TRAPS", desc: "Sub-$2 auth charges silently converting to full billing cycles." },
        { title: "DUPLICATE TOOLING", desc: "Multiple teams paying separately for the same vendor." },
        { title: "STATIC BURN METRICS", desc: "Single runway date with no volatility modelling for real decisions." }
      ],
      systemIdea: "EVERY ALERT IS A DATABASE ENTITY WITH EVIDENCE. NOT A NOTIFICATION. NOT A GUESS.",
      coreEngine: [
        { title: "GHOST HUNTER", desc: "Relational join between transactions and employees table. Flags 100% reclaimable spend.", icon: <Layers className="w-4 h-4" /> },
        { title: "TRIAL SENTINEL", desc: "Time-series check for sub-$2 auths followed by subscription-pattern charges.", icon: <AlertCircle className="w-4 h-4" /> },
        { title: "DUPLICATE SCANNER", desc: "Detects same normalised vendor billed across multiple cards in the same cycle.", icon: <CheckCircle2 className="w-4 h-4" /> },
        { title: "DRIFT DETECTOR", desc: "Multi-month spend analysis surfacing silent vendor cost inflation over time.", icon: <Activity className="w-4 h-4" /> }
      ],
      hitl: [
        { step: "01", title: "CONFIDENCE SCORING", desc: "Ghost license is 100% reclaimable. Tool overlap scores 40%. User sees confidence before deciding." },
        { step: "02", title: "FOUNDER LOOP", desc: "Every alert requires explicit Waste or Valid Use Case confirmation before any action is taken." },
        { step: "03", title: "LEARNING EXEMPTIONS", desc: "Marking Valid writes a permanent exemption rule. Engine never re-flags that pattern." }
      ],
      dataEngine: {
        steps: [
          { title: "DIRECT DB INGESTION", desc: "Financial data flows directly from connected database sources into a normalised stream." },
          { title: "CANONICALISATION ENGINE", desc: "Fuzzy matching maps chaotic vendor strings to unified canonical entities." },
          { title: "FORENSIC LAYER", desc: "Normalised transactions joined against HRIS data via deterministic SQL logic." }
        ]
      },
      stack: [
        { category: "FRONTEND", items: ["Next.js 14", "TypeScript", "React", "Tailwind CSS", "Framer Motion"] },
        { category: "BACKEND", items: ["Supabase", "PostgreSQL", "Server Actions", "Zod"] },
        { category: "DATA / AI", items: ["Gemini 1.5 API", "alertsEngine.ts", "Fuzzy Matching Engine"] },
        { category: "TOOLING", items: ["Vercel", "GitHub", "Claude"] }
      ],
      highlights: [
        { title: "DETERMINISTIC DETECTION", desc: "Zero ML guessing. Every waste alert is generated by strict SQL logic with evidence IDs." },
        { title: "DIRECT DATA PIPELINE", desc: "Live database connection ensures detection engine operates on current data." },
        { title: "STATE-DRIVEN ALERT ROWS", desc: "Alerts are persistent PostgreSQL entities linked to source transactions." }
      ],
      reality: {
        built: ["Direct DB ingestion pipeline", "8-detector forensic alert engine", "Gemini-powered grounded AI analyst"],
        mocked: ["Live third-party connector integrations", "System timeline autonomous events"],
        gap: ["Composite unique constraint mapping", "Exemption rules table persistence", "Runway variance math"]
      },
      roadmap: [
        { step: "01", title: "IDEMPOTENCY HARDENING", desc: "Composite unique index to prevent double-counting on duplicate records." },
        { step: "02", title: "EXEMPTION PERSISTENCE", desc: "Build exemption rules table so dismissed alerts are permanently remembered." },
        { step: "03", title: "VARIANCE CONE", desc: "Refactor runway engine to output Optimistic, Expected, and Pessimistic paths." },
        { step: "04", title: "EVENT-DRIVEN ALERTS", desc: "Supabase DB triggers firing the alert engine automatically on inserts." }
      ]
    }
  },
  resolveos: {
    name: "ResolveOS",
    systemNumber: "03 // SYSTEM",
    subheading: "SUPPORT OPERATIONS // CAPACITY ENGINE",
    description: "Dual-surface support operations platform that replaces chronological inboxes with intelligent capacity-aware routing, SLA enforcement, and real-time load balancing — managing agents as much as it manages tickets.",
    image: "/projects/resolveos.png",
    accent: "#FACC15",
    sections: {
      need: "Standard support inboxes are chronological and context-blind — high-value enterprise clients churn when their critical requests are buried under low-priority noise. ResolveOS replaces the inbox model with a deterministic priority engine that guarantees revenue-critical issues are always handled first.",
      painPoints: [
        { title: "INBOX BLINDNESS", desc: "Chronological queues treat a cancellation request the same as a password reset." },
        { title: "AGENT OVERLOAD", desc: "No visibility into who is overwhelmed and who has capacity, causing uneven burnout." },
        { title: "SLA BREACHES", desc: "No enforcement mechanism means enterprise tickets miss deadlines silently." },
        { title: "AI DEPENDENCY RISK", desc: "Systems that route via AI break entirely when the LLM is unavailable." }
      ],
      systemIdea: "RESOLVEOS DOESN'T JUST MANAGE TICKETS. IT MANAGES THE HUMANS HANDLING THEM.",
      coreEngine: [
        { title: "FAST-PASS BYPASS", desc: "Enterprise domains and cancellation keywords trigger instant escalation, skipping AI classification.", icon: <Zap className="w-4 h-4" /> },
        { title: "WEIGHTED QUEUE PROCESSOR", desc: "Processes tickets in a 5:1 priority ratio ensuring high-urgency tickets dominate without starvation.", icon: <Layers className="w-4 h-4" /> },
        { title: "LOAD SCORER", desc: "Agent workload calculated by priority-weighted active ticket count helping to prevent burnout.", icon: <Activity className="w-4 h-4" /> },
        { title: "SLA STATE MACHINE", desc: "Delayed job queues enforce deadline transitions. Breached tickets trigger escalation automatically.", icon: <ArrowUpRight className="w-4 h-4" /> }
      ],
      hitl: [
        { step: "01", title: "EXPLAINABLE ROUTING", desc: "Every auto-assignment logs a human-readable reason for match and current load score." },
        { step: "02", title: "REBALANCE RECOMMENDATIONS", desc: "Admin reviews surfaced capacity imbalances and suggested reassignments before applying." },
        { step: "03", title: "MANUAL OVERRIDE", desc: "Agents and admins can reassign, escalate, or reprioritise at any point with full activity logs." }
      ],
      dataEngine: {
        steps: [
          { title: "TICKET INGESTION", desc: "Incoming tickets handled idempotently via event ID hashing and PostgreSQL UNIQUE enforcement." },
          { title: "CLASSIFICATION & ROUTING", desc: "Synchronous regex fast-pass runs first; remaining tickets are classified by AI based on tier." },
          { title: "ASSIGNMENT ENGINE", desc: "Matches ticket skill tags against lowest weighted load score and persists the reasoning engine." }
        ]
      },
      stack: [
        { category: "FRONTEND", items: ["Next.js 14", "TypeScript", "React", "Tailwind CSS", "Framer Motion"] },
        { category: "BACKEND", items: ["Supabase", "PostgreSQL", "Server Actions", "React Query"] },
        { category: "AI / LOGIC", items: ["OpenAI API", "Regex Classification", "Priority Queue Engine"] },
        { category: "TOOLING", items: ["Vercel", "GitHub", "Claude"] }
      ],
      highlights: [
        { title: "IDEMPOTENT WEBHOOKS", desc: "Composite unique constraints drop duplicate webhooks instantly with zero application logic." },
        { title: "CONCURRENCY CONTROL", desc: "Version-based conditional updates prevent race conditions across parallel escalation workers." },
        { title: "GRACEFUL DEGRADATION", desc: "Circuit breaker routes failing AI tasks to fallback queues while SLA timers remain active." }
      ],
      reality: {
        built: ["Dual-surface platform with role separation", "Priority-weighted routing engine", "SLA state machine with job queues"],
        mocked: ["Email and WhatsApp gateway integrations", "Background autonomous rebalancing"],
        gap: ["Rebalancing requires manual apply", "Email ingestion pipeline in early design"]
      },
      roadmap: [
        { step: "01", title: "AUTONOMOUS REBALANCING", desc: "Trigger reassignment when load delta between agents exceeds defined thresholds." },
        { step: "02", title: "BURNOUT DASHBOARD", desc: "Dedicated view showing individual agent load versus team average for self-regulation." },
        { step: "03", title: "EXTERNAL GATEWAYS", desc: "Email and WhatsApp ingestion pipelines for unified customer ticket creation." },
        { step: "04", title: "IMPACT ANALYTICS", desc: "Surfacing hours saved and SLA breach reduction to prove operational ROI." }
      ]
    }
  },
  hivestate: {
    name: "HiveState",
    systemNumber: "01 // SYSTEM",
    subheading: "AGENT ORCHESTRATION // OBSERVABILITY ENGINE",
    description: "Visual multi-agent orchestration platform that executes LLM pipelines with dependency-aware parallelism, full cost transparency, and production-grade resilience — turning autonomous AI into an inspectable, governable system.",
    image: "/projects/hivestate-visual.png",
    accent: "#FFD700",
    sections: {
      need: "Developers building multi-agent AI systems had no visibility into what their agents were actually doing — no cost breakdown, no failure context, no way to resume a crashed pipeline without starting over and re-billing completed steps. HiveState eliminates the black box entirely.",
      painPoints: [
        { title: "NO COST VISIBILITY", desc: "Agents burn API credits with zero per-step breakdown of what each call actually cost." },
        { title: "CRASH AND RESTART", desc: "A single agent failure forces the entire pipeline to restart from scratch." },
        { title: "OPAQUE FAILURES", desc: "No way to know which agent broke the chain or what payload caused it." },
        { title: "NO HUMAN CONTROL", desc: "Fully autonomous pipelines with no pause point for human review before critical steps." }
      ],
      systemIdea: "EVERY AGENT STEP IS INSPECTABLE, PAUSEABLE, AND COST-ACCOUNTED. NO BLACK BOXES.",
      coreEngine: [
        { title: "DAG EXECUTOR", desc: "Topological sort executes dependency-safe parallel branches concurrently without race conditions.", icon: <Cpu className="w-4 h-4" /> },
        { title: "CIRCUIT BREAKER", desc: "Monitors consecutive API failures and auto-pauses at threshold to prevent credit drain.", icon: <AlertCircle className="w-4 h-4" /> },
        { title: "X-RAY TRACER", desc: "Captures raw prompt, completion, token split, and micro-cost per node — full transparency.", icon: <Activity className="w-4 h-4" /> },
        { title: "RESUME ENGINE", desc: "Idempotent fingerprinting persists every successful step for failure-point resumption.", icon: <Database className="w-4 h-4" /> }
      ],
      hitl: [
        { step: "01", title: "HITL NODES", desc: "Special pipeline nodes that freeze execution and surface current output for human review." },
        { step: "02", title: "APPROVE OR CORRECT", desc: "Reviewer approves to continue or rejects with a correction note injected into next agent context." },
        { step: "03", title: "AUDIT TRAIL", desc: "Every HITL event is logged in the trace with timestamp, decision, and correction note." }
      ],
      dataEngine: {
        steps: [
          { title: "RUN INTERFACE", desc: "User submits prompt via execution panel. System generates compressed intent summary." },
          { title: "DAG EXECUTION ENGINE", desc: "Nodes execute in topologically sorted order. Independent branches run in parallel." },
          { title: "STATE PERSISTENCE", desc: "Every node completion writes immediately to PostgreSQL trace logs with full token/cost metadata." }
        ]
      },
      stack: [
        { category: "FRONTEND", items: ["Next.js 14", "TypeScript", "React Flow", "Tailwind CSS", "Framer Motion"] },
        { category: "BACKEND", items: ["Supabase", "PostgreSQL", "Server Actions", "REST APIs"] },
        { category: "AI / ORCHESTRATION", items: ["Gemini 1.5 API", "Google AI SDK", "Multi-agent DAG Engine"] },
        { category: "TOOLING", items: ["Vercel", "GitHub", "Claude"] }
      ],
      highlights: [
        { title: "IDEMPOTENT EXECUTION", desc: "Completed steps are skipped on resume — no duplicate execution, no re-billing successful agents." },
        { title: "PARALLEL DEPENDENCY SAFETY", desc: "In-degree map guarantees nodes only execute when all parents are persisted." },
        { title: "CONTEXT COMPRESSION", desc: "Compressed intent summary propagated to preserves context window across long pipelines." }
      ],
      reality: {
        built: ["DAG parallel execution engine", "X-Ray trace with per-node token/cost", "Pause/resume state machine with HITL nodes"],
        mocked: ["Multi-provider model switching", "External alert dispatch on circuit breaker"],
        gap: ["Vercel serverless execution timeouts", "Lack of persistent background worker cluster"]
      },
      roadmap: [
        { step: "01", title: "MERGER NODE", desc: "Structured JSON bundling of multiple parent outputs for reliable multi-source pipelines." },
        { step: "02", title: "MULTI-PROVIDER", desc: "Live model switching per node between Gemini, OpenAI, and Anthropic." },
        { step: "03", title: "BACKGROUND WORKER", desc: "Persistent execution on dedicated infra eliminating serverless timeout constraints." },
        { step: "04", title: "COST FORECASTING", desc: "Pre-run token estimation per pipeline based on model selection and history." }
      ]
    }
  }
};

const CardSection = ({ title, items = [], renderCard, gridCols = "md:grid-cols-2", maxVisible = 4 }: { title: string, items?: any[], renderCard: (item: any, idx: number) => React.ReactNode, gridCols?: string, maxVisible?: number }) => {
  const [page, setPage] = useState(0);
  const totalItems = items?.length || 0;
  const totalPages = Math.ceil(totalItems / maxVisible);
  const currentItems = items?.slice(page * maxVisible, (page + 1) * maxVisible) || [];

  return (
    <div className="mb-16">
      <div className="flex items-center justify-between mb-8">
        <h3 className="font-bebas text-2xl tracking-[0.2em] text-white/50 uppercase">{title}</h3>
        {totalPages > 1 && (
          <div className="flex items-center gap-3">
             <span className="font-outfit text-[10px] font-bold text-white/20 tracking-widest">{page + 1} / {totalPages}</span>
             <div className="flex gap-1">
                <button 
                  onClick={() => setPage(p => Math.max(0, p - 1))}
                  disabled={page === 0}
                  className="p-1.5 rounded-full border border-white/10 hover:bg-white/5 disabled:opacity-20 transition-all"
                >
                  <ChevronLeft className="w-3 h-3 text-white" />
                </button>
                <button 
                  onClick={() => setPage(p => Math.min(totalPages - 1, p + 1))}
                  disabled={page === totalPages - 1}
                  className="p-1.5 rounded-full border border-white/10 hover:bg-white/5 disabled:opacity-20 transition-all"
                >
                  <ChevronRight className="w-3 h-3 text-white" />
                </button>
             </div>
          </div>
        )}
      </div>
      <div className={cn("grid gap-4", gridCols)}>
        <AnimatePresence mode="wait">
          <motion.div 
            key={page}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.3 }}
            className={cn("grid gap-4 contents")}
          >
            {currentItems.map((item, i) => renderCard(item, i))}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
};

export function CaseStudyOverlay({ projectId }: CaseStudyOverlayProps) {
  const { setActiveProject } = useSection();
  const overlayRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    container: overlayRef,
  });

  // Use the prop passed from the parent to ensure data persists during exit animation
  const project = projectId ? PROJECTS_DATA[projectId] : null;

  const handleNavigate = (direction: "prev" | "next") => {
    if (!projectId) return;
    const currentIndex = PROJECT_ORDER.indexOf(projectId);
    let nextIndex;
    
    if (direction === "next") {
      nextIndex = (currentIndex + 1) % PROJECT_ORDER.length;
    } else {
      nextIndex = (currentIndex - 1 + PROJECT_ORDER.length) % PROJECT_ORDER.length;
    }
    
    setActiveProject(PROJECT_ORDER[nextIndex]);
    
    // Scroll the content panel back to top on navigation
    if (overlayRef.current) {
      overlayRef.current.scrollTo({ top: 0, behavior: "smooth" });
    }
  };

  // Moving useTransform here - outside of conditional returns
  const imageY = useTransform(scrollYProgress, [0, 1], [0, 0]); // Set to 0 to disable parallax as requested

  if (!project) return null;

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[1000] flex items-center justify-center p-4 md:p-8"
    >
      {/* Lightened Backdrop - Show Aurora */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ 
          opacity: 1,
          backgroundColor: projectId === 'hivestate' ? "rgba(0, 0, 0, 0.6)" : "rgba(0, 0, 0, 0.2)"
        }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.4 }}
        onClick={() => setActiveProject(null)}
        className={cn(
          "absolute inset-0 backdrop-blur-[2px]",
          projectId === 'hivestate' && "backdrop-blur-[8px]"
        )}
      />

      {/* Main Container */}
      <motion.div 
        initial={{ opacity: 0, y: 20, scale: 0.97, filter: "blur(8px)" }}
        animate={{ opacity: 1, y: 0, scale: 1, filter: "blur(0px)" }}
        exit={{ 
          opacity: 0, 
          y: 40, 
          scale: 0.95, 
          filter: "blur(10px)",
          transition: { duration: 0.4, ease: "easeIn" }
        }}
        transition={{ 
          duration: 0.7, 
          ease: [0.22, 1, 0.36, 1] // Premium ease-out
        }}
        className="relative w-full h-full max-w-7xl bg-[#0E0E0E] border border-white/10 rounded-[32px] overflow-hidden flex flex-col md:flex-row shadow-[0_0_100px_rgba(0,0,0,0.8)]"
      >
        {/* Back Button */}
        <button 
          onClick={() => setActiveProject(null)}
          className="absolute top-8 left-8 z-[100] flex items-center gap-3 font-bebas text-sm tracking-[0.3em] text-white/40 hover:text-white transition-all group"
        >
          <div className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-black/40 backdrop-blur-md transition-transform group-hover:-translate-x-1">
             <ChevronLeft className="w-4 h-4" />
          </div>
          BACK TO SYSTEMS
        </button>

        {/* Left Visual Panel - Strictly Sticky */}
        <div className="w-full md:w-[42%] h-[40vh] md:h-full relative overflow-hidden flex-shrink-0">
          <motion.div 
             className="absolute inset-0"
             style={{ y: imageY }}
          >
            <Image 
              src={project.image} 
              alt={project.name} 
              fill
              className="object-cover"
              priority
            />
            <div className="absolute inset-0 bg-gradient-to-t from-[#0E0E0E] via-transparent to-transparent opacity-60" />
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent to-[#0E0E0E]/40" />
          </motion.div>
          
          <div className="absolute top-8 right-8">
             <button className="flex h-10 w-10 items-center justify-center rounded-full border border-white/20 bg-black/40 backdrop-blur-md text-white/60 hover:text-white hover:scale-110 transition-all">
                <ArrowUpRight className="w-5 h-5" />
             </button>
          </div>
        </div>

        {/* Right Content Panel - Scrollable (Compact View) */}
        <div 
          ref={overlayRef}
          className="flex-1 h-full overflow-y-auto scroll-smooth scrollbar-hide bg-[#0E0E0E] relative"
        >
          <div className="px-6 md:px-12 pt-16 pb-12 max-w-2xl">
            {/* HERO BLOCK */}
            <div className="mb-12">
               <div className="flex items-center gap-3 mb-2">
                  <span className="font-bebas text-sm tracking-[0.4em] text-yellow-400">
                    {project.systemNumber || "01 // SYSTEM"}
                  </span>
               </div>
               <h1 className="font-bebas text-5xl md:text-7xl text-white leading-none mb-3 tracking-tight uppercase">
                 {project.name}
               </h1>
                <div className="mb-6">
                  <p className="font-outfit text-xs md:text-sm font-bold text-yellow-400/60 uppercase tracking-[0.3em] inline-block py-1 px-2.5 border border-yellow-400/10 rounded bg-yellow-400/5">
                    {project.subheading}
                  </p>
                </div>
               <p className="font-outfit text-lg md:text-xl text-neutral-300 font-medium leading-relaxed">
                 {project.description}
               </p>
            </div>

            {/* THE NEED */}
            <div className="mb-12">
              <div className="h-[1px] w-10 bg-yellow-400/30 mb-6" />
              <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-4">THE NEED</h3>
              <div className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
                <p className="font-outfit text-md text-neutral-400 leading-relaxed italic">
                  “{project.sections.need}”
                </p>
              </div>
            </div>

            {/* PAIN POINTS */}
            {project.sections.painPoints && (
              <CardSection 
                title="PAIN POINTS"
                items={project.sections.painPoints}
                renderCard={(item, i) => (
                  <div key={i} className="p-6 rounded-xl border border-white/5 bg-white/[0.01] hover:bg-white/[0.03] transition-all">
                     <h4 className="font-bebas text-xl text-white mb-2 tracking-wider">• {item.title}</h4>
                     <p className="font-outfit text-sm text-neutral-400 font-medium leading-relaxed">{item.desc}</p>
                  </div>
                )}
              />
            )}

            {/* SYSTEM IDEA */}
            <div className="py-24 text-center border-y border-white/5 mb-20">
                <p className="font-bebas text-3xl md:text-5xl text-white tracking-widest leading-tight uppercase max-w-2xl mx-auto">
                   “{project.sections.systemIdea}”
                </p>
            </div>

            {/* CORE ENGINE */}
            {project.sections.coreEngine && (
              <CardSection 
                title="CORE ENGINE"
                items={project.sections.coreEngine}
                renderCard={(item, i) => (
                  <div key={i} className="p-5 rounded-xl border border-yellow-400/10 bg-yellow-400/[0.02] group hover:border-yellow-400/30 transition-all flex flex-col gap-2">
                    <div className="text-yellow-400 group-hover:scale-110 transition-transform w-fit h-4 w-4">
                        {item.icon}
                    </div>
                    <div>
                        <h4 className="font-bebas text-lg text-yellow-400 mb-0.5 tracking-wider uppercase">{item.title}</h4>
                        <p className="font-outfit text-xs text-neutral-400 font-medium leading-relaxed">{item.desc}</p>
                    </div>
                  </div>
                )}
              />
            )}



            {/* HUMAN IN THE LOOP (BURNSIGHT) */}
            {project.sections.hitl && (
              <div className="mb-16">
                <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-6">HUMAN-IN-THE-LOOP (HITL)</h3>
                <div className="flex flex-col md:flex-row gap-4">
                    {project.sections.hitl.map((item, i) => (
                      <div key={i} className="flex-1 relative">
                        <div className="flex items-center gap-3 mb-3">
                            <span className="font-bebas text-2xl text-white/10">{item.step}</span>
                            <div className="h-[1px] flex-1 bg-white/5" />
                        </div>
                        <h4 className="font-bebas text-lg text-white mb-1 tracking-wider uppercase">{item.title}</h4>
                        <p className="font-outfit text-[10px] text-neutral-500 font-bold leading-relaxed tracking-wide">{item.desc}</p>
                      </div>
                    ))}
                </div>
              </div>
            )}

            {/* DATA ENGINE (BURNSIGHT) */}
            {project.sections.dataEngine && (
              <div className="mb-16 p-8 rounded-2xl border border-white/5 bg-gradient-to-br from-white/[0.03] to-transparent">
                <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-6">DATA FLOW ARCHITECTURE</h3>
                <div className="space-y-6">
                  {project.sections.dataEngine.steps.map((step, i) => (
                    <div key={i} className="flex gap-4 items-start">
                        <div className="flex-shrink-0 w-8 h-8 rounded-full border border-white/10 flex items-center justify-center font-bebas text-md text-white">
                          {i + 1}
                        </div>
                        <div>
                          <h4 className="font-bebas text-lg text-white mb-0.5 tracking-wider uppercase">{step.title}</h4>
                          <p className="font-outfit text-xs text-neutral-400 leading-relaxed">{step.desc}</p>
                        </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* STACK & TOOLS */}
            <div className="mb-16">
               <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-6">STACK & TOOLS</h3>
               <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {project.sections.stack.map((cat, i) => (
                    <div key={i} className="space-y-3">
                        <h4 className="font-outfit text-[9px] font-bold text-white/40 tracking-[0.4em] uppercase">{cat.category}</h4>
                        <div className="flex flex-wrap gap-2">
                           {cat.items.map((item: string, j: number) => (
                             <div key={j} className="px-2 py-1 rounded-md border border-white/5 bg-white/[0.02] font-outfit text-[10px] font-bold text-neutral-300">
                                {item}
                             </div>
                           ))}
                        </div>
                    </div>
                  ))}
               </div>
            </div>

            {/* ENGINEERING HIGHLIGHTS (BURNSIGHT) */}
            {project.sections.highlights && (
              <div className="mb-16">
                <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-6">ENGINEERING HIGHLIGHTS</h3>
                <div className="space-y-3">
                  {project.sections.highlights.map((h, i) => (
                    <div key={i} className="group p-4 rounded-xl border border-white/5 bg-white/[0.01] hover:border-yellow-400/20 transition-all flex items-center gap-4">
                       <div className="w-1.5 h-1.5 rounded-full bg-yellow-400 shadow-[0_0_10px_rgba(255,215,0,0.5)]" />
                       <div className="flex-1">
                          <h4 className="font-bebas text-lg text-white mb-0.5 tracking-wider uppercase">{h.title}</h4>
                          <p className="font-outfit text-[10px] text-neutral-500 font-bold tracking-tight">{h.desc}</p>
                       </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* EXECUTION REALITY (BUILDER SIGNAL) */}
            <div className="mb-16">
               <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-6">REALITY CHECK</h3>
               <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="space-y-3">
                     <div className="flex items-center gap-2 text-green-400 mb-1">
                        <CheckCircle2 className="w-3 h-3" />
                        <span className="font-bebas text-xs tracking-widest uppercase">BUILT</span>
                     </div>
                     {(project.sections.execution?.built || project.sections.reality?.built).map((item: string, i: number) => (
                       <div key={i} className="font-outfit text-xs text-neutral-400 font-medium">— {item}</div>
                     ))}
                  </div>
                  <div className="space-y-3">
                     <div className="flex items-center gap-2 text-yellow-500 mb-1">
                        <Info className="w-3 h-3" />
                        <span className="font-bebas text-xs tracking-widest uppercase">MOCKED</span>
                     </div>
                     {(project.sections.execution?.mocked || project.sections.reality?.mocked).map((item: string, i: number) => (
                       <div key={i} className="font-outfit text-xs text-neutral-400 font-medium">— {item}</div>
                     ))}
                  </div>
                  <div className="space-y-3">
                     <div className="flex items-center gap-2 text-red-500 mb-1">
                        <AlertCircle className="w-3 h-3" />
                        <span className="font-bebas text-xs tracking-widest uppercase">{project.sections.execution ? 'LIMITATIONS' : 'GAP'}</span>
                     </div>
                     {(project.sections.execution?.limitations || project.sections.reality?.gap).map((item: string, i: number) => (
                       <div key={i} className="font-outfit text-xs text-neutral-400 font-medium">— {item}</div>
                     ))}
                  </div>
               </div>
            </div>

            {/* ROADMAP */}
            <div className="mb-16">
               <h3 className="font-bebas text-xl tracking-[0.2em] text-white/50 uppercase mb-6">ROADMAP</h3>
               <div className="relative pl-6 border-l border-white/10 space-y-8">
                  {project.sections.roadmap.map((item, i) => (
                    <div key={i} className="relative">
                       <div className="absolute -left-[29px] top-0 w-3 h-3 rounded-full bg-[#0E0E0E] border-2 border-yellow-400 shadow-[0_0_10px_rgba(255,215,0,0.4)]" />
                       <div className="font-bebas text-[10px] text-yellow-500 mb-0.5 tracking-widest">{item.step}</div>
                       <h4 className="font-bebas text-xl text-white mb-1 tracking-wider uppercase">{item.title}</h4>
                       <p className="font-outfit text-[11px] text-neutral-500 font-bold leading-relaxed">{item.desc}</p>
                    </div>
                  ))}
               </div>
            </div>

            {/* FOOTER NAV */}
            <div className="pt-12 border-t border-white/5 flex items-center justify-between">
               <button 
                onClick={() => handleNavigate("prev")}
                className="flex items-center gap-3 font-bebas text-md text-neutral-600 hover:text-white transition-colors uppercase tracking-widest"
               >
                 <ChevronLeft className="w-4 h-4" />
                 PREVIOUS
               </button>
               <button 
                onClick={() => handleNavigate("next")}
                className="flex items-center gap-3 font-bebas text-md text-neutral-600 hover:text-white transition-colors uppercase tracking-widest group"
               >
                 NEXT PROJECT
                 <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
               </button>
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
